# -*- coding: utf-8 -*-
"""ProblemSolving4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZc9XLcHJWr_AXsM0IWJD-4hkq9OQJq-
"""

#Inheritance is when characteristics of one class are passed on to another class.in the example below the class car inherits the method make from class vehicle as we have given the name vehicle while passing the argument while creating class car.
class vehicle:
  def make(self):
    return "motor vehicle"
class car(vehicle):
  def sound(self):
    return "horn"
c=car()
print(c.make())