# -*- coding: utf-8 -*-
"""ProblemSolving2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/145hG0Rw_GyTzyT5JBCkvj-P1-ozoReUt
"""

#Pep8 is a set of conventions or rules to increase the quality of code in Python.It depends on a number of factors like naming rules,following proper syntax,etc.
#PEP stands for Python Enhancement Proposal