# -*- coding: utf-8 -*-
"""ProblemSolving13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0EjzAHog9atAFulq_RMcC8f3SwiPcF8
"""

#self is a pointer which points to an instance of a class in pyhton