# -*- coding: utf-8 -*-
"""Problem Solving17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WcnxGLrktapyTYcToFoZwceUeb05arJk
"""

#single level inheritance is when one class is derived from another class,just give the class you want it to be derived from in arguments.
#multiple level inheritance is when one class is derived from more than one class,just give all the classes used for deriving while creating the child class
#Multi-Level Inheritance is when for instance,we have a grandparent class from which parent class is derived then the child class is derived from parent class.So,this is an example of Mukti-Level Inheritance.
#Hybrid inheritance is when a class is derived as a result of single-level inheritance then multiple level inheritance and finally Multi-level inheritance so it makes use of all the other types of inheritance.