# -*- coding: utf-8 -*-
"""problemSolving3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fe9UpQmVDamPujtDIEcn5fR_7NH3BL86
"""

#__init__ method is like a constructor which uses the self method to show the instance of a class and is used to allow for arguments while defining the object.