# -*- coding: utf-8 -*-
"""ProblemSoving16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13iPU5urmmRr1aIRgV2YsBG5gqszzHtkd
"""

#Encapsulation is implemented by passing ._ to a method to protect it and make it accesible only to the given class.
#Abstraction is passed by giving the foll. statement
#from abc import ABC,abstractmethod
#then passing ABC in arguments to the class you want to create as an abstract class and passing abstractmethod to the method you want to within the class given the ABC in arguments.
#different classes can have same or repeating methods so you can implement polymorphism by creating objects of the class you want and calling methods of the different classes.