# -*- coding: utf-8 -*-
"""ProblemSolving11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GEp4MOC1jRA-OgMSj4xC2RzprdFVfNZV
"""

#append method adds an element to the end of the list you can pass it to a list by using the list_name.append() with character or number inside brackets.
#extends method joins 2 lists together for example if you want to join a list li to list tr just give tr.extends(li) to combine both the lists.