# -*- coding: utf-8 -*-
"""ProblemSolving15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBUwEB2QavcMVp6Tx-BnwJ4WSAK2hYTl
"""

#class variable is a variable which is like any any other variable used to store a value like a number or a string
#instance of a class is used to access the methods inside the class and is also called an object.