# -*- coding: utf-8 -*-
"""ProblemSolving6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hTboO6ZO2Ahoz2Dwn326T3cClKMLNluI
"""

#Polymorphism is when the code takes different forms based on input.for example in an add function which return you the addition of 2 variables,if you give input string you'll get combination of string and if you give numbers you will get addition of 2 numbers.