# -*- coding: utf-8 -*-
"""ProblemSolving1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xpab5mM8VsB7-JXuk6wxsLLa7hfaE3mE
"""

#lists are defined in square brackets.li below is an example of list.they are mutable.
li=[1,"abc",3,4]
#tuples are given in round brackets and immutable.tu below is an example of a tuple.
tu=(1,3,5,8)