# -*- coding: utf-8 -*-
"""Pythonsolution7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbzCTYEpShs0lN9rkIvNsnAEPSLGhyKe
"""

#we use try keyword for the lines of code we want to run and subsequently give the statement except exception as e and you can print(e) to display the error in the output