# -*- coding: utf-8 -*-
"""PythonSolution5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-pOH_OfjgiR0L59ddJLTB4vZGQpn1ko
"""

#Class method is used to update a data member or variable inside a class by using the object
#static method is used to update values directly without using an object.